### ISSUE TITLE
Update project to work with React v15+

### ISSUE THREAD

**Issue by victorporof** [web-perf/react-worker-dom#12]

**Comment by axemclion** [comment]
At the moment, looks like the Fiber renderer may change how the work is offloaded to a web worker. I was waiting for that to land, before moving it to React v15.

**Comment by oskarer** [comment]
You can use the r-15 branch for React 15.x, but it's experimental and incomplete.

**Comment by axemclion** [comment]
I think we can close this issue, since @oskarer is working on r15.
