### ISSUE TITLE
Using with Redux

### ISSUE THREAD

**Issue by FredyC** [web-perf/react-worker-dom#7]
I cannot seem to find source code for your demos, so I am wondering how the state management works. Is there local state within components? Either way I would like to see some proper demo used with Redux. 

I mean if I want Redux to stay on main thread and have React only to be rendered in worker, how could I achieve a communication? It's hard to imagine that I would be passing whole state there because that means serialize and deserialize causing new object every time and the performance gain gets lowered right away due to React optimizations.

Am I missing something obvious? I haven't been using workers for some time, so perhaps there are some new methods how to pass data around?

**Comment by axemclion** [comment]
@FredyC The demo source code is under the [test folder](https://github.com/web-perf/react-worker-dom/tree/master/test). At the moment, it uses local state management. 

The state could also be moved to the worker thread - is there a reason to keep the state in the main UI thread ?

**Comment by FredyC** [comment]
@axemclion What if the state needs to be shared with other part of the app? Or what if some actions need to be dispatched from the non-worker part?

To give you an example, we have a WebGL game along with React/Redux based UI. It would be really helpful to have UI running in the worker so it wont take away performance from game itself. However as you can imagine there would be quite a lot of intercommunication between these layers. User does something in UI which changes state and this change should be propagated back to game engine. 

Actions are most probably the best way to communicate as they are transient and doesn't hold any real state. It would have to be duplex communication as some game action can change state of UI and user doing something in UI would influence game itself.

I guess this could work for easy cases. The game engine would hold its own state relevant to game engine changed by its own reducers. Same would be applied to UI thread keeping state relevant to UI only. However things are not always that ideal and some data might be rather duplicate, eg. some game stats that should be visible in UI, but are also relevant for game engine calculations. For some speed operations there might be even some delays in display.

In my opinion for this project to be really useful, it needs to solve this, but I am not sure I can come up with good enough solution, I don't feel that bright...

**Comment by danielkcz** [comment]
I guess this will be obsolete soon with fibers :)
