### ISSUE TITLE
not work in a real project

### ISSUE THREAD

**Issue by gagayang** [web-perf/react-worker-dom#9]
i think this is only a demo,not work in a real project. Leadership let me study the use of webworker to optimize the efficiency of the react project, but the current use of the react project is to use a lot of plug-ins, you can not use this project seems to be the use of plug-ins. I would like to ask you if there is no real project to use?

**Comment by axemclion** [comment]
@gagayang What are the plugins that do not work ?

**Comment by MrZaYaC** [comment]
In my case, when I import `react-worker-dom` webpack do not compile your project. Also this project is not in npm. Looks like it is really only for demo

**Comment by axemclion** [comment]
@MrZaYaC I am currently working on updating this for React 15.x . What is the error you get when you are trying to compile the project ?

**Comment by MrZaYaC** [comment]
@axemclion I got no errors, just `import` stay `import`, Webpack didn`t compile to ES5 your project.
Here is my config
```js
alias: {
    'react-worker-dom': path.resolve(__dirname, 'node_modules/react-worker-dom/src/page/index.js'),
    'react-worker-dom-worker': path.resolve(__dirname, 'node_modules/react-worker-dom/src/worker/index.js')
            }
```
```js
    test: /\.jsx?$/,
    loader: 'babel',
    exclude: /node_modules/,
    include: [/node_modules\/react-worker-dom/],
    query: {
        presets: ['react', 'es2015', 'stage-0']
    }
```

Error:

```
Uncaught SyntaxError: Unexpected token import

function(module, exports) {

	import React from 'react';
	import reactDOM from 'react-worker-dom'; // Instead of using react-dom
	reactDOM.render(new Worker('worker.bundle.js'), document.getElementById('app'));

}
```

**Comment by MrZaYaC** [comment]
@axemclion Could you please publish your project to npm with compiled dist, so we can import your project like normal people? Thanx

**Comment by jpdevries** [comment]
I'm following the Usage instruction but something is unclear to me

`import ReactWorkerDOM from 'react-worker-dom-worker';`

I see that the test example Webpack server is mapping `react-worker-dom-worker` to `'./../src/worker/index.js`. Am I supposed to have to do something like that?
